#!/usr/bin/env bash

echo 'global execution start...'
echo "All args: $*"
echo "Received arg1: $1"
echo "Received arg2: $2"
echo -e 'global execution end...\n'

test_func() {
    echo 'function execution start...'
    echo "All args: $*"
    echo "Received arg1: $1"
    echo "Received arg2: $2"
    echo 'function execution end...'
}

test_func Arg1 Arg2