#!/usr/bin/env bash

arr=(1 2 3 4 5)
arr2=(banana bread 'cut pineaple' pie)

echo "${arr[1]}"
echo "${arr[-1]}"
arr2[1]=tomato
arr2+=('grape')
unset arr2[0]
echo "${arr2[*]}"
echo "${#arr2[@]}" # "*" and "@" same
echo "${arr2[@]:1:2}"