#!/usr/bin/env bash

declare -i a
declare -i b

read -p "Enter devident: " x
read -p "Enter devider: " y

a="${x//[^0-9]/}"
b="${y//[^0-9]/}"

int_part=$(( a / b ))
remainder=$(( a % b ))

echo -n "${int_part}"
if [ $remainder -ne 0 ]; then
    echo -n " ${remainder}/${b}"
fi
echo