#!/bin/bash

declare -r green="$(tput setaf 2)"
declare -r bold="$(tput bold)"
declare -r reset="$(tput sgr0)"

read -p "Enter your name: " name

echo "Hi ${green}${bold}${name}${reset}!"

items=$(ls ~/Desktop | wc -l)
echo "You have $items items in Your Desktop folder"

echo '---------------------------------------'
