#!/usr/bin/env bash

declare -i errors_count=0
declare -i iterator=0
url=https://downloads.codingcoursestv.eu/055%20-%20bash/while/images/image-%%.jpg
assets_path=../assets/%%.jpg

while (( errors_count < 10 )); do
    (( iterator = iterator + 1 ))
    if ! curl -fso "${assets_path/\%\%/$iterator}" "${url/\%\%/$iterator}"; then
        (( errors_count = errors_count + 1 ))
        echo "download error ${errors_count}"
    else
        errors_count=0
        echo 'download success'
    fi
done

echo "done"