#!/usr/bin/env bash

echo 'first loop'
for i in 1 2 3 4 5; do
    echo "$i"
done

echo -e '\nsecond loop'
for i in {1..10..2}; do
    echo "$i"
done

echo -e '\nthird loop'
for filename in *.{txt,csv}; do
    echo "$filename"
done
